#############################################################################
# Makefile for building: mandelbrot.app/Contents/MacOS/mandelbrot
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  mandelbrot.pro
# Template: app
# Command: /Users/jesse/Qt/5.8/clang_64/bin/qmake -o Makefile mandelbrot.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang -F/Users/jesse/Qt/5.8/clang_64/lib
QMAKE         = /Users/jesse/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mandelbrot1.0.0
DISTDIR = /Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot/.tmp/mandelbrot1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Users/jesse/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jesse/Qt/5.8/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mandelbrotwidget.cpp \
		renderthread.cpp moc_mandelbrotwidget.cpp \
		moc_renderthread.cpp
OBJECTS       = main.o \
		mandelbrotwidget.o \
		renderthread.o \
		moc_mandelbrotwidget.o \
		moc_renderthread.o
DIST          = /Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		mandelbrot.pro mandelbrotwidget.h \
		renderthread.h main.cpp \
		mandelbrotwidget.cpp \
		renderthread.cpp
QMAKE_TARGET  = mandelbrot
DESTDIR       = 
TARGET        = mandelbrot.app/Contents/MacOS/mandelbrot


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d mandelbrot.app/Contents/MacOS/ || mkdir -p mandelbrot.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mandelbrot.pro /Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/jesse/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		mandelbrot.pro \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile mandelbrot.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qt.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/resources.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/moc.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/uic.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Users/jesse/Qt/5.8/clang_64/mkspecs/features/lex.prf:
mandelbrot.pro:
/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mandelbrot.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

mandelbrot.app/Contents/PkgInfo: 
	@test -d mandelbrot.app/Contents || mkdir -p mandelbrot.app/Contents
	@$(DEL_FILE) mandelbrot.app/Contents/PkgInfo
	@echo "APPL????" > mandelbrot.app/Contents/PkgInfo
mandelbrot.app/Contents/Resources/empty.lproj: 
	@test -d mandelbrot.app/Contents/Resources || mkdir -p mandelbrot.app/Contents/Resources
	@touch mandelbrot.app/Contents/Resources/empty.lproj
	
mandelbrot.app/Contents/Info.plist: 
	@test -d mandelbrot.app/Contents || mkdir -p mandelbrot.app/Contents
	@$(DEL_FILE) mandelbrot.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.mandelbrot,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,mandelbrot,g" -e "s,@LIBRARY@,mandelbrot,g" -e "s,@TYPEINFO@,????,g" /Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >mandelbrot.app/Contents/Info.plist

all: Makefile \
		mandelbrot.app/Contents/PkgInfo \
		mandelbrot.app/Contents/Resources/empty.lproj \
		mandelbrot.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/jesse/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mandelbrotwidget.h renderthread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mandelbrotwidget.cpp renderthread.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mandelbrot.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/jesse/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Users/jesse/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mandelbrotwidget.cpp moc_renderthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mandelbrotwidget.cpp moc_renderthread.cpp
moc_mandelbrotwidget.cpp: /Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		renderthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QMutex \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSize \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		mandelbrotwidget.h \
		moc_predefs.h \
		/Users/jesse/Qt/5.8/clang_64/bin/moc
	/Users/jesse/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot -I/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/jesse/Qt/5.8/clang_64/lib mandelbrotwidget.h -o moc_mandelbrotwidget.cpp

moc_renderthread.cpp: /Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QMutex \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSize \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		renderthread.h \
		moc_predefs.h \
		/Users/jesse/Qt/5.8/clang_64/bin/moc
	/Users/jesse/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/jesse/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot -I/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/jesse/Qt/5.8/clang_64/lib renderthread.h -o moc_renderthread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mandelbrotwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		renderthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QMutex \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSize \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mandelbrotwidget.o: mandelbrotwidget.cpp /Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPainter \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qevent.h \
		mandelbrotwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QPixmap \
		/Users/jesse/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		renderthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QMutex \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSize \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandelbrotwidget.o mandelbrotwidget.cpp

renderthread.o: renderthread.cpp renderthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QMutex \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSize \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsize.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QThread \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QWaitCondition \
		/Users/jesse/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QtWidgets \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsglobal.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractitemdelegate.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractscrollarea.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractslider.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qabstractspinbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qaccessiblewidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcalendarwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcheckbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcolormap.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcolumnview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcommandlinkbutton.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcommonstyle.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qcompleter.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdatawidgetmapper.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdatetimeedit.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdesktopwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdial.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdialogbuttonbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdirmodel.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdockwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qdrawutil.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qerrormessage.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfileiconprovider.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfilesystemmodel.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfocusframe.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qfontdialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qformlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgesture.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgesturerecognizer.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsanchorlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsgridlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicslayoutitem.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicslinearlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsproxywidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicstransform.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicswidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qheaderview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qitemdelegate.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qitemeditorfactory.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qkeyeventtransition.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qkeysequenceedit.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlayoutitem.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlistview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmdiarea.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmdisubwindow.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmenubar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmouseeventtransition.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qopenglwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qplaintextedit.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressbar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qprogressdialog.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qproxystyle.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qrubberband.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qscroller.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qscrollerproperties.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qshortcut.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsizepolicy.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qslider.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qspinbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsplitter.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstackedwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstyle.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstyleditemdelegate.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstylefactory.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstylepainter.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qstyleplugin.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtabbar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtableview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtabwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtoolbox.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtoolbutton.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtreeview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtreewidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtreewidgetitemiterator.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qundogroup.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qundostack.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qundoview.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwhatsthis.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwidgetaction.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		/Users/jesse/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderthread.o renderthread.cpp

moc_mandelbrotwidget.o: moc_mandelbrotwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mandelbrotwidget.o moc_mandelbrotwidget.cpp

moc_renderthread.o: moc_renderthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderthread.o moc_renderthread.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot || mkdir -p $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot
	$(DEL_FILE) -r $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot/mandelbrot.app
	
	-$(INSTALL_DIR) mandelbrot.app $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot/mandelbrot.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot/mandelbrot.app
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/jesse/Qt/Examples/Qt-5.8/corelib/threads/mandelbrot/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

